image: docker:stable

stages:
 - build
 - test
 - deploy

services:
- docker:dind

build:
  script:
    # install composer and get dependencies
    - echo $CI_ENVIRONMENT_SLUG
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.mijnproject.nu
    - docker build -t ${CI_REGISTRY}/bumblebee/api:build-${CI_COMMIT_REF_SLUG} --build-arg NPM_INSTALL_BEFORE=true -f docker/Dockerfile ./
    - docker push ${CI_REGISTRY}/bumblebee/api:build-${CI_COMMIT_REF_SLUG}


# Push the image to Docker Swarm as service and run a rolling deploy
push to production:
  image: docker:stable
  stage: deploy
  variables:
    DOCKER_HOST: tcp://192.168.178.30:2375
  image: docker:latest
  script:
    - echo $CI_ENVIRONMENT_SLUG
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.mijnproject.nu
    - docker stack deploy --prune --resolve-image=always --with-registry-auth --compose-file=docker-stack-compose.yml ${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}
  environment:
    name: api-bumblebee-fm
    url: https://api.bumblebee.fm
  only:
    - master
