image: docker:stable

stages:
 - build
 - test
 - deploy

services:
- docker:dind

build:
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE} --build-arg NPM_INSTALL_BEFORE=true -f docker/Dockerfile ./
    - docker push ${CI_REGISTRY_IMAGE}

# Push the image to Docker Swarm as service and run a rolling deploy
push to production:
  image: docker:stable
  stage: deploy
  variables:
    DOCKER_HOST: tcp://192.168.178.48:2375
  image: docker:latest
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $CI_REGISTRY
    - docker stack deploy --prune --resolve-image=always --with-registry-auth --compose-file=docker-stack-compose.yml ${CI_PROJECT_NAMESPACE}-${CI_PROJECT_NAME}
  environment:
    name: api-bumblebee-fm
    url: https://api.bumblebee.fm
  only:
    - master
