version: '3'
services:
    api:
        build:
            context: ./
            dockerfile: docker/Dockerfile
            args:
                - NPM_INSTALL_BEFORE=false
        volumes:
            - ./:/var/www/html
        depends_on:
           - mongodb
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - USE_NODEMON=true
            - NPM_INSTALL_AFTER=false
        ports:
            - 3000:3000
        networks:
          - bumblebee-net
            
    mongodb:
        image: mongo:3.4
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - db_mongodb:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        networks:
          - bumblebee-net
    
networks:
    bumblebee-net:
        driver: bridge
volumes:
  db_mongodb: