version: '3'
services:
 
    api:
        image: ${CI_REGISTRY_IMAGE}
        environment:
            - MONGO_HOST=192.168.178.48
            - MONGO_PORT=27017
            - USE_NODEMON=false
            - NPM_INSTALL_AFTER=false
        ports:
            - 3000:3000
        volumes:
            - "/share/nas/bumblebee/audio/:/var/www/html/dist/audio/"
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s