version: '3'
services:
 
    api:
        build: ./api/docker
        volumes:
            - ./api:/var/www/html
        depends_on:
            - mongodb
        environment:
            - MONGO_HOST=192.168.178.29
            - MONGO_PORT=27017
        ports:
            - 3000:3000

    discord:
        build: ./discord/docker
        volumes:
            - ./discord:/var/www/html
        environment:
            - NODE_ENV=development
            - API_HOST=api
            - API_PORT=3000
        container_name: "discord"
        depends_on:
            - api

    website:
        build:
            context: ./website/docker/
            dockerfile: Dockerfile
            args:
                - DOCKER_SRC="./"
        environment:
            - NODE_ENV=production
            - ANGULAR_ENV=prod
        ports:
            - 80:80
        depends_on:
            - api
volumes:
  db_data:
