version: '3.7'
services:
    api:
        image: ${CI_REGISTRY_IMAGE}:latest
        environment:
            - NODE_ENV=production
            - MONGO_HOST=$DB_HOST
            - MONGO_PORT=$DB_PORT
            - LOG_LEVEL=info
            - REDIS_HOST=redis
        networks:
          - proxy-net
          - bmbl-net
        volumes:
            - "/mnt/cluster/nas/bumblebee/audio:/var/www/html/dist/audio/"
        deploy:
            labels:
              - traefik.enable=true
              - traefik.http.routers.http-api-bmbl-cloud.rule=Host(`api.bmbl.cloud`) || Host(`api.bmbl.mijnproject.nu`)
              - traefik.http.routers.https-api-bmbl-cloud.rule=Host(`api.bmbl.cloud`) || Host(`api.bmbl.mijnproject.nu`)
              - traefik.http.routers.https-api-bmbl-cloud.tls=true
              - traefik.http.routers.https-api-bmbl-cloud.tls.certresolver=myresolver             
              - traefik.http.services.bmbl-api-svc.loadbalancer.server.port=3000
            restart_policy:
                delay: 30s
            replicas: 3
            update_config:
                parallelism: 2
            resources:
                limits:
                    cpus: '1.0'
                    memory: 1024M
                reservations:
                    cpus: '0.5'
                    memory: 128M
    redis:
      image: redis
      networks:
          - bmbl-net
      deploy:
          restart_policy:
              delay: 30s
          replicas: 1
          update_config:
              parallelism: 2
          resources:
              limits:
                  cpus: '1.0'
                  memory: 1024M
              reservations:
                  cpus: '0.5'
                  memory: 128M      

networks:
   bmbl-net:
   proxy-net:
      external: true
