version: '3.7'
services:
    api:
        image: ${CI_REGISTRY_IMAGE}:latest
        environment:
            - NODE_ENV=production
            - MONGO_HOST=$DB_HOST
            - MONGO_PORT=$DB_PORT
            - LOG_LEVEL=info
        ports:
            - 3000:3000
        volumes:
            - "audio_volume:/var/www/html/dist/audio/"
        deploy:
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
            placement:
                constraints: [node.role == manager]


volumes:
  audio_volume:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=192.168.25.10,rw"
      device: ":/volume3/docker/bumblebee/audio"