version: '3'
services:
 
    api:
        build:
            context: ./api
            dockerfile: docker/Dockerfile
            args:
                - NPM_INSTALL_BEFORE=false
        volumes:
            - ./api:/var/www/html
        depends_on:
            - mongodb
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
        ports:
            - 3000:3000

    discord:
        build: 
            context: ./discord
            dockerfile: docker/Dockerfile
            args:
                - NPM_INSTALL_BEFORE=false
        volumes:
            - ./discord:/var/www/html
        environment:
            - NODE_ENV=development
            - API_HOST=api
            - API_PORT=3000
        container_name: "discord"
        depends_on:
            - api

    website:
        build:
            context: ./website
            dockerfile: docker/Dockerfile
            args:
                - NPM_INSTALL_BEFORE=false
        environment:
            - NODE_ENV=development
            - ANGULAR_ENV=dev
            - NG_OPTIONAL=--watch=true --poll
        volumes:
            - ./website:/var/www/html
        ports:
            - 80:80
        depends_on:
            - api
    mongodb:
        image: mongo:3.4
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
