version: '3.7'
services:
    # api:
    #     build:
    #         context: ./
    #         dockerfile: docker/Dockerfile
    #         args:
    #             - NPM_GLOBAL_PACKAGES=typescript nodemon
    #             - BUILD_PROD=false
    #     volumes:
    #         - ./:/var/www/html
    #         - ./node_modules:/var/www/html/node_modules:delegated
    #     depends_on:
    #        - mongodb
    #     environment:
    #         - MONGO_HOST=mongodb
    #         - MONGO_PORT=27017
    #         - NODE_ENV=development
    #     ports:
    #         - 3000:3000
    #     networks:
    #       - bumblebee-net
    # mongodb:
    #     image: mongo:latest
    #     container_name: "mongodb"
    #     environment:
    #         - MONGO_DATA_DIR=/data/db
    #         - MONGO_LOG_DIR=/dev/null
    #     volumes:
    #         - db_mongodb:/data/db
    #     ports:
    #         - 27017:27017
    #     command: mongod --quiet
    #     networks:
    #       - bumblebee-net
    redis:
        ports:
          - 6379:6379 
        image: redis
        networks:
          - bumblebee-net
networks:
    bumblebee-net:
        driver: bridge
volumes:
  db_mongodb: