@startuml Creation of new fragments
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu

title Creation of new fragments

|#White|Client|
start
:GET all existing words by text;

|#AntiqueWhite|API|
:Return words;

|Client|
:POST words that don't exist yet;

|API|
:Return words;

|Client|
:Link word ids to (unsaved) fragments;
:POST fragments;

|API|
:Process fragments;

|Client|
:Update UI;
stop

@enduml