@startuml
!includeurl https://raw.githubusercontent.com/matthewjosephtaylor/plantuml-style/master/style.pu
' skinparam backgroundColor #1E1E1E

participant ExternalUser

ExternalUser -> App: Invokes tts

activate App

App -> API: POST /v1/externaluser
activate API

API --> App: 200 OK

activate App
App -> API: POST /v1/tts
API -> App: Done

deactivate API

App -> ExternalUser: Play tts
deactivate App

@enduml